version: 2.1

executors:
  main:
    docker:
      - image: cimg/python:3.7

commands:
  install-package:
    steps:
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv
            source .venv/bin/activate
            make install

  install-package-docs:
    steps:
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv
            source .venv/bin/activate
            poetry install 
            pip install -r docs/requirements.txt

  setup-poetry:
    steps:
      - run:
          name: Install poetry
          command: |
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
            echo 'export PATH="$HOME/.poetry/bin:$PATH"' >> $BASH_ENV

  persist-coverage:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - .coverage
            - coverage.xml

  report-codecov:
    steps:
      - attach_workspace:
          at: .
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  build_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
              - build
      - docs:
          requires:
              - build
      - codecov:
          requires:
              - test

jobs:
  build:
    executor: main
    steps:
      - checkout 
      - setup-poetry
      - run:
          name: Build package artifacts
          command: poetry build
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - dist/htmxl-0.8.2.tar.gz
            - dist/htmxl-0.8.2-py3-none-any.whl

  test:
    executor: main
    steps:
      - checkout 
      - attach_workspace:
          at: .
      - install-package
      - run:
          name: Unit Test
          command: |
            source .venv/bin/activate
            make test
      - persist-coverage

  lint:
    executor: main
    steps:
      - checkout 
      - attach_workspace:
          at: .
      - install-package
      - run:
          name: Lint
          command: |
            source .venv/bin/activate
            make lint

  docs:
    executor: main
    steps:
      - checkout 
      - attach_workspace:
          at: .
      - install-package-docs
      - run:
          name: Build Docs
          command: |
            source .venv/bin/activate
            make -C docs html
      - persist_to_workspace:
          root: .
          paths:
            - docs/_build/*

  codecov:
    executor: main
    steps:
      - report-codecov
