version: 2.1

executors:
  main:
    docker:
      - image: schireson/cicd-python37
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD


commands:
  setup:
    steps:
      - checkout 
      - run: |
          mkdir ~/.pip
          echo -e "[global]\nindex-url = https://artifactory.schireson.com/artifactory/api/pypi/pypi/simple\ntrusted-host = artifactory.schireson.com" > ~/.pip/pip.conf

  aws-create-credentials:
    steps:
      - run:
          name: Create credentials file for AWS
          command: |
            aws configure set default.region "${AWS_DEFAULT_REGION:-us-east-1}"
            printf "${AWS_CREDENTIALS}" > ~/.aws/credentials

  install-package:
    steps:
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv
            source .venv/bin/activate
            lucha aws whitelist --profile artifactory -- pip install dist/schireson-excel-0.7.3.tar.gz[testing]

  install-package-docs:
    steps:
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv
            source .venv/bin/activate
            lucha aws whitelist --profile artifactory -- pip install dist/schireson-excel-0.7.3.tar.gz[docs]


workflows:
  build_test_publish:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
              - build
      - docs:
          requires:
              - build
      - publish:
          requires:
            - build
            - lint
            - test
            - docs
          filters:
            branches:
              only:
                - /^master$/

jobs:
  build:
    executor: main
    steps:
      - setup
      - run:
          name: Build package artifacts
          command: python setup.py sdist bdist_wheel
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - dist/schireson-excel-0.7.3.tar.gz
            - dist/schireson_excel-0.7.3-py3-none-any.whl

  test:
    executor: main
    steps:
      - setup
      - attach_workspace:
          at: .
      - aws-create-credentials
      - install-package
      - run:
          name: Unit Test
          command: |
            source .venv/bin/activate
            make test

  lint:
    executor: main
    steps:
      - setup
      - attach_workspace:
          at: .
      - aws-create-credentials
      - install-package
      - run:
          name: Lint
          command: |
            source .venv/bin/activate
            make lint

  docs:
    executor: main
    steps:
      - setup
      - attach_workspace:
          at: .
      - aws-create-credentials
      - install-package-docs
      - run:
          name: Build Docs
          command: |
            source .venv/bin/activate
            make -C docs html
      - persist_to_workspace:
          root: .
          paths:
            - docs/_build/*

  publish:
    executor: main
    steps:
      - setup
      - attach_workspace:
          at: .
      - aws-create-credentials
      - run:
          name: Publish Python Distribution to Artifactory
          command: |
            lucha aws whitelist --profile artifactory -- lucha cicd publish pypi --no-build
            lucha cicd publish docs --latest --profile ruby-docs --package schireson-excel
