version: 2.1

executors:
  main:
    docker:
      - image: cimg/python:3.7

commands:
  install-package:
    steps:
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv
            source .venv/bin/activate
            pip install dist/htmxl-0.8.0.tar.gz[testing]

  install-package-docs:
    steps:
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv
            source .venv/bin/activate
            pip install dist/htmxl-0.8.0.tar.gz[docs]


workflows:
  build_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
              - build
      - docs:
          requires:
              - build

jobs:
  build:
    executor: main
    steps:
      - checkout 
      - run:
          name: Build package artifacts
          command: python setup.py sdist bdist_wheel
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - dist/htmxl-0.8.0.tar.gz
            - dist/htmxl-0.8.0-py3-none-any.whl

  test:
    executor: main
    steps:
      - checkout 
      - attach_workspace:
          at: .
      - install-package
      - run:
          name: Unit Test
          command: |
            source .venv/bin/activate
            make test

  lint:
    executor: main
    steps:
      - checkout 
      - attach_workspace:
          at: .
      - install-package
      - run:
          name: Lint
          command: |
            source .venv/bin/activate
            make lint

  docs:
    executor: main
    steps:
      - checkout 
      - attach_workspace:
          at: .
      - install-package-docs
      - run:
          name: Build Docs
          command: |
            source .venv/bin/activate
            make -C docs html
      - persist_to_workspace:
          root: .
          paths:
            - docs/_build/*
